//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Launcher.rc
//
#define IDD_LAUNCHER_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDC_BUTTON_GO                   1001
#define IDC_COMBOBOX_PLAYER_CAR         1002
#define IDC_COMBOBOX_PLAYER_SKIN        1003
#define IDC_COMBOBOX_PLAYER_MODE_VALUE  1004
#define IDC_COMBOBOX_PLAYER_MODE_UPDOWN 1005
#define IDC_CHECK_OPPONENT_SAME_AS_PLAYER 1006
#define IDC_COMBOBOX_OPPONENT_CAR       1007
#define IDC_COMBOBOX_OPPONENT_SKIN      1008
#define IDC_COMBOBOX_OPPONENT_COUNT     1009
#define IDC_COMBOBOX_OPPONENT_DIFFICULTY 1010
#define IDC_COMBOBOX_TRACK_TRACK        1011
#define IDC_COMBOBOX_TRACK_LAPS_VALUE   1012
#define IDC_COMBOBOX_TRACK_LAPS_UPDOWN  1013
#define IDC_CHECK_TRACK_NIGHT           1014
#define IDC_CHECK_TRACK_WEATHER         1015
#define IDC_CHECK_TRACK_NO_DAMAGE       1016
#define IDC_CHECK_TRACK_MIRRORED        1017
#define IDC_CHECK_TRACK_BACKWARD        1018
#define IDC_CHECK_TRACK_TRAFFIC         1019
#define IDC_BUTTON_SAVE                 1020
#define IDC_BUTTON_EXIT                 1021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
