/*
Copyright (c) 2025 Americus Maximus

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "Images.hxx"

#include <Graphics.Basic.hxx>

const ImageTest ImageTests[MAX_IMAGE_TEST_CASES] =
{
    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   FALSE, FALSE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    FALSE, FALSE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   FALSE, TRUE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    FALSE, TRUE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   FALSE, FALSE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    FALSE, FALSE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   FALSE, TRUE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    FALSE, TRUE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, 0x00FABECD,              FALSE, FALSE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, 0x00FABECD,               FALSE, FALSE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, 0x00FABECD,              FALSE, TRUE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, 0x00FABECD,               FALSE, TRUE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, 0xFFFABECD,              FALSE, FALSE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, 0xFFFABECD,               FALSE, FALSE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, 0xFFFABECD,              FALSE, TRUE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, 0xFFFABECD,               FALSE, TRUE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   TRUE, FALSE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    TRUE, FALSE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   TRUE, TRUE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    TRUE, TRUE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   TRUE, FALSE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    TRUE, FALSE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   TRUE, TRUE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    TRUE, TRUE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, 0x00FABECD,              TRUE, FALSE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, 0x00FABECD,               TRUE, FALSE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, 0x00FABECD,              TRUE, TRUE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, 0x00FABECD,               TRUE, TRUE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, 0xFFFABECD,              TRUE, FALSE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, 0xFFFABECD,               TRUE, FALSE, COLORSCHEMA_BLACK },

    { 128, 128, FALSE, 0xFFFABECD,              TRUE, TRUE, COLORSCHEMA_BLACK },
    { 128, 128, TRUE, 0xFFFABECD,               TRUE, TRUE, COLORSCHEMA_BLACK },


    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   FALSE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    FALSE, FALSE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   FALSE, TRUE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    FALSE, TRUE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   FALSE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    FALSE, FALSE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   FALSE, TRUE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    FALSE, TRUE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, 0x00FABECD,              FALSE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, 0x00FABECD,               FALSE, FALSE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, 0x00FABECD,              FALSE, TRUE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, 0x00FABECD,               FALSE, TRUE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, 0xFFFABECD,              FALSE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, 0xFFFABECD,               FALSE, FALSE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, 0xFFFABECD,              FALSE, TRUE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, 0xFFFABECD,               FALSE, TRUE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   TRUE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    TRUE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   TRUE, TRUE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    TRUE, TRUE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   TRUE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    TRUE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   TRUE, TRUE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    TRUE, TRUE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, 0x00FABECD,              TRUE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, 0x00FABECD,               TRUE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, FALSE, 0x00FABECD,              TRUE, TRUE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, 0x00FABECD,               TRUE, TRUE, COLORSCHEMA_WHITE },

    { 128, 128, FALSE, 0xFFFABECD,              TRUE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, 0xFFFABECD,               TRUE, FALSE, COLORSCHEMA_WHITE },
    { 128, 128, FALSE, 0xFFFABECD,              TRUE, TRUE, COLORSCHEMA_WHITE },
    { 128, 128, TRUE, 0xFFFABECD,               TRUE, TRUE, COLORSCHEMA_WHITE },


    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   FALSE, FALSE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    FALSE, FALSE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   FALSE, TRUE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    FALSE, TRUE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   FALSE, FALSE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    FALSE, FALSE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   FALSE, TRUE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    FALSE, TRUE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, 0x00FABECD,              FALSE, FALSE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, 0x00FABECD,               FALSE, FALSE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, 0x00FABECD,              FALSE, TRUE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, 0x00FABECD,               FALSE, TRUE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, 0xFFFABECD,              FALSE, FALSE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, 0xFFFABECD,               FALSE, FALSE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, 0xFFFABECD,              FALSE, TRUE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, 0xFFFABECD,               FALSE, TRUE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   TRUE, FALSE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    TRUE, FALSE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, GRAPCHICS_COLOR_BLACK,   TRUE, TRUE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, GRAPCHICS_COLOR_BLACK,    TRUE, TRUE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   TRUE, FALSE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    TRUE, FALSE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, GRAPCHICS_COLOR_WHITE,   TRUE, TRUE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, GRAPCHICS_COLOR_WHITE,    TRUE, TRUE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, 0x00FABECD,              TRUE, FALSE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, 0x00FABECD,               TRUE, FALSE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, 0x00FABECD,              TRUE, TRUE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, 0x00FABECD,               TRUE, TRUE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, 0xFFFABECD,              TRUE, FALSE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, 0xFFFABECD,               TRUE, FALSE, COLORSCHEMA_REPEAT },

    { 128, 128, FALSE, 0xFFFABECD,              TRUE, TRUE, COLORSCHEMA_REPEAT },
    { 128, 128, TRUE, 0xFFFABECD,               TRUE, TRUE, COLORSCHEMA_REPEAT },


    { 512, 512, FALSE, GRAPCHICS_COLOR_BLACK,   FALSE, FALSE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, GRAPCHICS_COLOR_BLACK,    FALSE, FALSE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, GRAPCHICS_COLOR_BLACK,   FALSE, TRUE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, GRAPCHICS_COLOR_BLACK,    FALSE, TRUE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, GRAPCHICS_COLOR_WHITE,   FALSE, FALSE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, GRAPCHICS_COLOR_WHITE,    FALSE, FALSE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, GRAPCHICS_COLOR_WHITE,   FALSE, TRUE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, GRAPCHICS_COLOR_WHITE,    FALSE, TRUE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, 0x00FABECD,              FALSE, FALSE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, 0x00FABECD,               FALSE, FALSE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, 0x00FABECD,              FALSE, TRUE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, 0x00FABECD,               FALSE, TRUE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, 0xFFFABECD,              FALSE, FALSE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, 0xFFFABECD,               FALSE, FALSE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, 0xFFFABECD,              FALSE, TRUE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, 0xFFFABECD,               FALSE, TRUE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, GRAPCHICS_COLOR_BLACK,   TRUE, FALSE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, GRAPCHICS_COLOR_BLACK,    TRUE, FALSE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, GRAPCHICS_COLOR_BLACK,   TRUE, TRUE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, GRAPCHICS_COLOR_BLACK,    TRUE, TRUE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, GRAPCHICS_COLOR_WHITE,   TRUE, FALSE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, GRAPCHICS_COLOR_WHITE,    TRUE, FALSE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, GRAPCHICS_COLOR_WHITE,   TRUE, TRUE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, GRAPCHICS_COLOR_WHITE,    TRUE, TRUE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, 0x00FABECD,              TRUE, FALSE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, 0x00FABECD,               TRUE, FALSE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, 0x00FABECD,              TRUE, TRUE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, 0x00FABECD,               TRUE, TRUE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, 0xFFFABECD,              TRUE, FALSE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, 0xFFFABECD,               TRUE, FALSE, COLORSCHEMA_IMAGE },

    { 512, 512, FALSE, 0xFFFABECD,              TRUE, TRUE, COLORSCHEMA_IMAGE },
    { 512, 512, TRUE, 0xFFFABECD,               TRUE, TRUE, COLORSCHEMA_IMAGE },
};
